server:
  port: 9860
  session:
    timeout: 10
#配置数据源
spring:
  datasource:
    name: platform
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://172.19.3.129:3306/mydb?characterEncoding=utf8&useSSL=false
    username: root
    password: Iot#10086
    driverClassName: com.mysql.jdbc.Driver
    minIdle: 1
    maxActive: 5
    initialSize: 1
    timeBetweenEvictionRunsMillis: 3000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
  redis:
    cluster:
      nodes:
        - 172.19.3.135:6379
        - 172.19.3.136:6379
        - 172.19.3.137:6379
mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.chinamobile.iot.lightapp.mysql.model


