package com.chinamobile.iot.lightapp.mysql.model;

import java.io.Serializable;

public class Applys implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column applys.apply_id
     *
     * @mbg.generated
     */
    private Integer applyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column applys.apply_user
     *
     * @mbg.generated
     */
    private Integer applyUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column applys.inviter
     *
     * @mbg.generated
     */
    private Integer inviter;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column applys.cycle_id
     *
     * @mbg.generated
     */
    private String cycleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column applys.apply_type
     *
     * @mbg.generated
     */
    private Integer applyType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table applys
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column applys.apply_id
     *
     * @return the value of applys.apply_id
     *
     * @mbg.generated
     */
    public Integer getApplyId() {
        return applyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column applys.apply_id
     *
     * @param applyId the value for applys.apply_id
     *
     * @mbg.generated
     */
    public void setApplyId(Integer applyId) {
        this.applyId = applyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column applys.apply_user
     *
     * @return the value of applys.apply_user
     *
     * @mbg.generated
     */
    public Integer getApplyUser() {
        return applyUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column applys.apply_user
     *
     * @param applyUser the value for applys.apply_user
     *
     * @mbg.generated
     */
    public void setApplyUser(Integer applyUser) {
        this.applyUser = applyUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column applys.inviter
     *
     * @return the value of applys.inviter
     *
     * @mbg.generated
     */
    public Integer getInviter() {
        return inviter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column applys.inviter
     *
     * @param inviter the value for applys.inviter
     *
     * @mbg.generated
     */
    public void setInviter(Integer inviter) {
        this.inviter = inviter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column applys.cycle_id
     *
     * @return the value of applys.cycle_id
     *
     * @mbg.generated
     */
    public String getCycleId() {
        return cycleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column applys.cycle_id
     *
     * @param cycleId the value for applys.cycle_id
     *
     * @mbg.generated
     */
    public void setCycleId(String cycleId) {
        this.cycleId = cycleId == null ? null : cycleId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column applys.apply_type
     *
     * @return the value of applys.apply_type
     *
     * @mbg.generated
     */
    public Integer getApplyType() {
        return applyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column applys.apply_type
     *
     * @param applyType the value for applys.apply_type
     *
     * @mbg.generated
     */
    public void setApplyType(Integer applyType) {
        this.applyType = applyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table applys
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", applyId=").append(applyId);
        sb.append(", applyUser=").append(applyUser);
        sb.append(", inviter=").append(inviter);
        sb.append(", cycleId=").append(cycleId);
        sb.append(", applyType=").append(applyType);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}