package com.chinamobile.iot.lightapp.mysql.model;

import java.io.Serializable;

public class Diagrams implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column diagrams.diagram_id
     *
     * @mbg.generated
     */
    private Integer diagramId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column diagrams.diagram_name
     *
     * @mbg.generated
     */
    private String diagramName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column diagrams.diagram_content
     *
     * @mbg.generated
     */
    private String diagramContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column diagrams.cycle_id
     *
     * @mbg.generated
     */
    private Integer cycleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column diagrams.diagram_type
     *
     * @mbg.generated
     */
    private Integer diagramType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table diagrams
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column diagrams.diagram_id
     *
     * @return the value of diagrams.diagram_id
     *
     * @mbg.generated
     */
    public Integer getDiagramId() {
        return diagramId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column diagrams.diagram_id
     *
     * @param diagramId the value for diagrams.diagram_id
     *
     * @mbg.generated
     */
    public void setDiagramId(Integer diagramId) {
        this.diagramId = diagramId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column diagrams.diagram_name
     *
     * @return the value of diagrams.diagram_name
     *
     * @mbg.generated
     */
    public String getDiagramName() {
        return diagramName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column diagrams.diagram_name
     *
     * @param diagramName the value for diagrams.diagram_name
     *
     * @mbg.generated
     */
    public void setDiagramName(String diagramName) {
        this.diagramName = diagramName == null ? null : diagramName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column diagrams.diagram_content
     *
     * @return the value of diagrams.diagram_content
     *
     * @mbg.generated
     */
    public String getDiagramContent() {
        return diagramContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column diagrams.diagram_content
     *
     * @param diagramContent the value for diagrams.diagram_content
     *
     * @mbg.generated
     */
    public void setDiagramContent(String diagramContent) {
        this.diagramContent = diagramContent == null ? null : diagramContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column diagrams.cycle_id
     *
     * @return the value of diagrams.cycle_id
     *
     * @mbg.generated
     */
    public Integer getCycleId() {
        return cycleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column diagrams.cycle_id
     *
     * @param cycleId the value for diagrams.cycle_id
     *
     * @mbg.generated
     */
    public void setCycleId(Integer cycleId) {
        this.cycleId = cycleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column diagrams.diagram_type
     *
     * @return the value of diagrams.diagram_type
     *
     * @mbg.generated
     */
    public Integer getDiagramType() {
        return diagramType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column diagrams.diagram_type
     *
     * @param diagramType the value for diagrams.diagram_type
     *
     * @mbg.generated
     */
    public void setDiagramType(Integer diagramType) {
        this.diagramType = diagramType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table diagrams
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", diagramId=").append(diagramId);
        sb.append(", diagramName=").append(diagramName);
        sb.append(", diagramContent=").append(diagramContent);
        sb.append(", cycleId=").append(cycleId);
        sb.append(", diagramType=").append(diagramType);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}