package com.chinamobile.iot.lightapp.mysql.model;

import java.io.Serializable;
import java.util.Date;

public class Notices implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notices.notice_id
     *
     * @mbg.generated
     */
    private Integer noticeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notices.notice_name
     *
     * @mbg.generated
     */
    private String noticeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notices.notice_content
     *
     * @mbg.generated
     */
    private String noticeContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notices.cycle_id
     *
     * @mbg.generated
     */
    private Integer cycleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notices.create_date
     *
     * @mbg.generated
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notices.update_date
     *
     * @mbg.generated
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table notices
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notices.notice_id
     *
     * @return the value of notices.notice_id
     *
     * @mbg.generated
     */
    public Integer getNoticeId() {
        return noticeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notices.notice_id
     *
     * @param noticeId the value for notices.notice_id
     *
     * @mbg.generated
     */
    public void setNoticeId(Integer noticeId) {
        this.noticeId = noticeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notices.notice_name
     *
     * @return the value of notices.notice_name
     *
     * @mbg.generated
     */
    public String getNoticeName() {
        return noticeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notices.notice_name
     *
     * @param noticeName the value for notices.notice_name
     *
     * @mbg.generated
     */
    public void setNoticeName(String noticeName) {
        this.noticeName = noticeName == null ? null : noticeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notices.notice_content
     *
     * @return the value of notices.notice_content
     *
     * @mbg.generated
     */
    public String getNoticeContent() {
        return noticeContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notices.notice_content
     *
     * @param noticeContent the value for notices.notice_content
     *
     * @mbg.generated
     */
    public void setNoticeContent(String noticeContent) {
        this.noticeContent = noticeContent == null ? null : noticeContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notices.cycle_id
     *
     * @return the value of notices.cycle_id
     *
     * @mbg.generated
     */
    public Integer getCycleId() {
        return cycleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notices.cycle_id
     *
     * @param cycleId the value for notices.cycle_id
     *
     * @mbg.generated
     */
    public void setCycleId(Integer cycleId) {
        this.cycleId = cycleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notices.create_date
     *
     * @return the value of notices.create_date
     *
     * @mbg.generated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notices.create_date
     *
     * @param createDate the value for notices.create_date
     *
     * @mbg.generated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notices.update_date
     *
     * @return the value of notices.update_date
     *
     * @mbg.generated
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notices.update_date
     *
     * @param updateDate the value for notices.update_date
     *
     * @mbg.generated
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notices
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", noticeId=").append(noticeId);
        sb.append(", noticeName=").append(noticeName);
        sb.append(", noticeContent=").append(noticeContent);
        sb.append(", cycleId=").append(cycleId);
        sb.append(", createDate=").append(createDate);
        sb.append(", updateDate=").append(updateDate);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}