package com.chinamobile.iot.lightapp.mysql.model;

import java.io.Serializable;
import java.util.Date;

public class Periods implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column periods.period_id
     *
     * @mbg.generated
     */
    private Integer periodId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column periods.period_name
     *
     * @mbg.generated
     */
    private String periodName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column periods.start_time
     *
     * @mbg.generated
     */
    private Date startTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column periods.end_time
     *
     * @mbg.generated
     */
    private Date endTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column periods.cycle_id
     *
     * @mbg.generated
     */
    private Integer cycleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table periods
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column periods.period_id
     *
     * @return the value of periods.period_id
     *
     * @mbg.generated
     */
    public Integer getPeriodId() {
        return periodId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column periods.period_id
     *
     * @param periodId the value for periods.period_id
     *
     * @mbg.generated
     */
    public void setPeriodId(Integer periodId) {
        this.periodId = periodId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column periods.period_name
     *
     * @return the value of periods.period_name
     *
     * @mbg.generated
     */
    public String getPeriodName() {
        return periodName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column periods.period_name
     *
     * @param periodName the value for periods.period_name
     *
     * @mbg.generated
     */
    public void setPeriodName(String periodName) {
        this.periodName = periodName == null ? null : periodName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column periods.start_time
     *
     * @return the value of periods.start_time
     *
     * @mbg.generated
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column periods.start_time
     *
     * @param startTime the value for periods.start_time
     *
     * @mbg.generated
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column periods.end_time
     *
     * @return the value of periods.end_time
     *
     * @mbg.generated
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column periods.end_time
     *
     * @param endTime the value for periods.end_time
     *
     * @mbg.generated
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column periods.cycle_id
     *
     * @return the value of periods.cycle_id
     *
     * @mbg.generated
     */
    public Integer getCycleId() {
        return cycleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column periods.cycle_id
     *
     * @param cycleId the value for periods.cycle_id
     *
     * @mbg.generated
     */
    public void setCycleId(Integer cycleId) {
        this.cycleId = cycleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table periods
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", periodId=").append(periodId);
        sb.append(", periodName=").append(periodName);
        sb.append(", startTime=").append(startTime);
        sb.append(", endTime=").append(endTime);
        sb.append(", cycleId=").append(cycleId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}