package com.chinamobile.iot.lightapp.mysql.model;

import java.io.Serializable;

public class Photo implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column photo.photo_id
     *
     * @mbg.generated
     */
    private Integer photoId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column photo.photo_addr
     *
     * @mbg.generated
     */
    private String photoAddr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column photo.photo_type
     *
     * @mbg.generated
     */
    private Integer photoType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table photo
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column photo.photo_id
     *
     * @return the value of photo.photo_id
     *
     * @mbg.generated
     */
    public Integer getPhotoId() {
        return photoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column photo.photo_id
     *
     * @param photoId the value for photo.photo_id
     *
     * @mbg.generated
     */
    public void setPhotoId(Integer photoId) {
        this.photoId = photoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column photo.photo_addr
     *
     * @return the value of photo.photo_addr
     *
     * @mbg.generated
     */
    public String getPhotoAddr() {
        return photoAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column photo.photo_addr
     *
     * @param photoAddr the value for photo.photo_addr
     *
     * @mbg.generated
     */
    public void setPhotoAddr(String photoAddr) {
        this.photoAddr = photoAddr == null ? null : photoAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column photo.photo_type
     *
     * @return the value of photo.photo_type
     *
     * @mbg.generated
     */
    public Integer getPhotoType() {
        return photoType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column photo.photo_type
     *
     * @param photoType the value for photo.photo_type
     *
     * @mbg.generated
     */
    public void setPhotoType(Integer photoType) {
        this.photoType = photoType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table photo
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", photoId=").append(photoId);
        sb.append(", photoAddr=").append(photoAddr);
        sb.append(", photoType=").append(photoType);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}