package com.chinamobile.iot.lightapp.mysql.model;

import java.io.Serializable;

public class Photos implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column photos.photo_id
     *
     * @mbg.generated
     */
    private Integer photoId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column photos.photo_name
     *
     * @mbg.generated
     */
    private String photoName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column photos.photo_addr
     *
     * @mbg.generated
     */
    private String photoAddr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column photos.check_item_id
     *
     * @mbg.generated
     */
    private Integer checkItemId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table photos
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column photos.photo_id
     *
     * @return the value of photos.photo_id
     *
     * @mbg.generated
     */
    public Integer getPhotoId() {
        return photoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column photos.photo_id
     *
     * @param photoId the value for photos.photo_id
     *
     * @mbg.generated
     */
    public void setPhotoId(Integer photoId) {
        this.photoId = photoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column photos.photo_name
     *
     * @return the value of photos.photo_name
     *
     * @mbg.generated
     */
    public String getPhotoName() {
        return photoName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column photos.photo_name
     *
     * @param photoName the value for photos.photo_name
     *
     * @mbg.generated
     */
    public void setPhotoName(String photoName) {
        this.photoName = photoName == null ? null : photoName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column photos.photo_addr
     *
     * @return the value of photos.photo_addr
     *
     * @mbg.generated
     */
    public String getPhotoAddr() {
        return photoAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column photos.photo_addr
     *
     * @param photoAddr the value for photos.photo_addr
     *
     * @mbg.generated
     */
    public void setPhotoAddr(String photoAddr) {
        this.photoAddr = photoAddr == null ? null : photoAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column photos.check_item_id
     *
     * @return the value of photos.check_item_id
     *
     * @mbg.generated
     */
    public Integer getCheckItemId() {
        return checkItemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column photos.check_item_id
     *
     * @param checkItemId the value for photos.check_item_id
     *
     * @mbg.generated
     */
    public void setCheckItemId(Integer checkItemId) {
        this.checkItemId = checkItemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table photos
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", photoId=").append(photoId);
        sb.append(", photoName=").append(photoName);
        sb.append(", photoAddr=").append(photoAddr);
        sb.append(", checkItemId=").append(checkItemId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}