package com.chinamobile.iot.lightapp.mysql.model;

import java.io.Serializable;
import java.util.Date;

public class Report implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report.report_id
     *
     * @mbg.generated
     */
    private Integer reportId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report.report_name
     *
     * @mbg.generated
     */
    private String reportName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report.cycle_id
     *
     * @mbg.generated
     */
    private Integer cycleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report.region_id
     *
     * @mbg.generated
     */
    private Integer regionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report.period_id
     *
     * @mbg.generated
     */
    private Integer periodId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report.start_time
     *
     * @mbg.generated
     */
    private Date startTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report.end_time
     *
     * @mbg.generated
     */
    private Date endTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report.flag
     *
     * @mbg.generated
     */
    private Integer flag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table report
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report.report_id
     *
     * @return the value of report.report_id
     *
     * @mbg.generated
     */
    public Integer getReportId() {
        return reportId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report.report_id
     *
     * @param reportId the value for report.report_id
     *
     * @mbg.generated
     */
    public void setReportId(Integer reportId) {
        this.reportId = reportId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report.report_name
     *
     * @return the value of report.report_name
     *
     * @mbg.generated
     */
    public String getReportName() {
        return reportName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report.report_name
     *
     * @param reportName the value for report.report_name
     *
     * @mbg.generated
     */
    public void setReportName(String reportName) {
        this.reportName = reportName == null ? null : reportName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report.cycle_id
     *
     * @return the value of report.cycle_id
     *
     * @mbg.generated
     */
    public Integer getCycleId() {
        return cycleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report.cycle_id
     *
     * @param cycleId the value for report.cycle_id
     *
     * @mbg.generated
     */
    public void setCycleId(Integer cycleId) {
        this.cycleId = cycleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report.region_id
     *
     * @return the value of report.region_id
     *
     * @mbg.generated
     */
    public Integer getRegionId() {
        return regionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report.region_id
     *
     * @param regionId the value for report.region_id
     *
     * @mbg.generated
     */
    public void setRegionId(Integer regionId) {
        this.regionId = regionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report.period_id
     *
     * @return the value of report.period_id
     *
     * @mbg.generated
     */
    public Integer getPeriodId() {
        return periodId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report.period_id
     *
     * @param periodId the value for report.period_id
     *
     * @mbg.generated
     */
    public void setPeriodId(Integer periodId) {
        this.periodId = periodId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report.user_id
     *
     * @return the value of report.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report.user_id
     *
     * @param userId the value for report.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report.start_time
     *
     * @return the value of report.start_time
     *
     * @mbg.generated
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report.start_time
     *
     * @param startTime the value for report.start_time
     *
     * @mbg.generated
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report.end_time
     *
     * @return the value of report.end_time
     *
     * @mbg.generated
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report.end_time
     *
     * @param endTime the value for report.end_time
     *
     * @mbg.generated
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report.flag
     *
     * @return the value of report.flag
     *
     * @mbg.generated
     */
    public Integer getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report.flag
     *
     * @param flag the value for report.flag
     *
     * @mbg.generated
     */
    public void setFlag(Integer flag) {
        this.flag = flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", reportId=").append(reportId);
        sb.append(", reportName=").append(reportName);
        sb.append(", cycleId=").append(cycleId);
        sb.append(", regionId=").append(regionId);
        sb.append(", periodId=").append(periodId);
        sb.append(", userId=").append(userId);
        sb.append(", startTime=").append(startTime);
        sb.append(", endTime=").append(endTime);
        sb.append(", flag=").append(flag);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}