package com.chinamobile.iot.lightapp.mysql.model;

import java.io.Serializable;

public class ReportItem implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report_item.item_id
     *
     * @mbg.generated
     */
    private Integer itemId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report_item.item_name
     *
     * @mbg.generated
     */
    private String itemName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report_item.item_content
     *
     * @mbg.generated
     */
    private String itemContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report_item.report_id
     *
     * @mbg.generated
     */
    private Integer reportId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table report_item
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report_item.item_id
     *
     * @return the value of report_item.item_id
     *
     * @mbg.generated
     */
    public Integer getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report_item.item_id
     *
     * @param itemId the value for report_item.item_id
     *
     * @mbg.generated
     */
    public void setItemId(Integer itemId) {
        this.itemId = itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report_item.item_name
     *
     * @return the value of report_item.item_name
     *
     * @mbg.generated
     */
    public String getItemName() {
        return itemName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report_item.item_name
     *
     * @param itemName the value for report_item.item_name
     *
     * @mbg.generated
     */
    public void setItemName(String itemName) {
        this.itemName = itemName == null ? null : itemName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report_item.item_content
     *
     * @return the value of report_item.item_content
     *
     * @mbg.generated
     */
    public String getItemContent() {
        return itemContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report_item.item_content
     *
     * @param itemContent the value for report_item.item_content
     *
     * @mbg.generated
     */
    public void setItemContent(String itemContent) {
        this.itemContent = itemContent == null ? null : itemContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report_item.report_id
     *
     * @return the value of report_item.report_id
     *
     * @mbg.generated
     */
    public Integer getReportId() {
        return reportId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report_item.report_id
     *
     * @param reportId the value for report_item.report_id
     *
     * @mbg.generated
     */
    public void setReportId(Integer reportId) {
        this.reportId = reportId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_item
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", itemId=").append(itemId);
        sb.append(", itemName=").append(itemName);
        sb.append(", itemContent=").append(itemContent);
        sb.append(", reportId=").append(reportId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}