package com.chinamobile.iot.lightapp.mysql.model;

import java.io.Serializable;

public class WorkCycle implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_cycle.work_cycle_id
     *
     * @mbg.generated
     */
    private Integer workCycleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_cycle.work_cycle_name
     *
     * @mbg.generated
     */
    private String workCycleName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_cycle.img_addr
     *
     * @mbg.generated
     */
    private String imgAddr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table work_cycle
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_cycle.work_cycle_id
     *
     * @return the value of work_cycle.work_cycle_id
     *
     * @mbg.generated
     */
    public Integer getWorkCycleId() {
        return workCycleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_cycle.work_cycle_id
     *
     * @param workCycleId the value for work_cycle.work_cycle_id
     *
     * @mbg.generated
     */
    public void setWorkCycleId(Integer workCycleId) {
        this.workCycleId = workCycleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_cycle.work_cycle_name
     *
     * @return the value of work_cycle.work_cycle_name
     *
     * @mbg.generated
     */
    public String getWorkCycleName() {
        return workCycleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_cycle.work_cycle_name
     *
     * @param workCycleName the value for work_cycle.work_cycle_name
     *
     * @mbg.generated
     */
    public void setWorkCycleName(String workCycleName) {
        this.workCycleName = workCycleName == null ? null : workCycleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_cycle.img_addr
     *
     * @return the value of work_cycle.img_addr
     *
     * @mbg.generated
     */
    public String getImgAddr() {
        return imgAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_cycle.img_addr
     *
     * @param imgAddr the value for work_cycle.img_addr
     *
     * @mbg.generated
     */
    public void setImgAddr(String imgAddr) {
        this.imgAddr = imgAddr == null ? null : imgAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_cycle
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", workCycleId=").append(workCycleId);
        sb.append(", workCycleName=").append(workCycleName);
        sb.append(", imgAddr=").append(imgAddr);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}