package com.chinamobile.iot.lightapp.mysql.model;

import java.util.ArrayList;
import java.util.List;

public class WorkCycleExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table work_cycle
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table work_cycle
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table work_cycle
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_cycle
     *
     * @mbg.generated
     */
    public WorkCycleExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_cycle
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_cycle
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_cycle
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_cycle
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_cycle
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_cycle
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_cycle
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_cycle
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_cycle
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_cycle
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table work_cycle
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andWorkCycleIdIsNull() {
            addCriterion("work_cycle.work_cycle_id is null");
            return (Criteria) this;
        }

        public Criteria andWorkCycleIdIsNotNull() {
            addCriterion("work_cycle.work_cycle_id is not null");
            return (Criteria) this;
        }

        public Criteria andWorkCycleIdEqualTo(Integer value) {
            addCriterion("work_cycle.work_cycle_id =", value, "workCycleId");
            return (Criteria) this;
        }

        public Criteria andWorkCycleIdNotEqualTo(Integer value) {
            addCriterion("work_cycle.work_cycle_id <>", value, "workCycleId");
            return (Criteria) this;
        }

        public Criteria andWorkCycleIdGreaterThan(Integer value) {
            addCriterion("work_cycle.work_cycle_id >", value, "workCycleId");
            return (Criteria) this;
        }

        public Criteria andWorkCycleIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("work_cycle.work_cycle_id >=", value, "workCycleId");
            return (Criteria) this;
        }

        public Criteria andWorkCycleIdLessThan(Integer value) {
            addCriterion("work_cycle.work_cycle_id <", value, "workCycleId");
            return (Criteria) this;
        }

        public Criteria andWorkCycleIdLessThanOrEqualTo(Integer value) {
            addCriterion("work_cycle.work_cycle_id <=", value, "workCycleId");
            return (Criteria) this;
        }

        public Criteria andWorkCycleIdIn(List<Integer> values) {
            addCriterion("work_cycle.work_cycle_id in", values, "workCycleId");
            return (Criteria) this;
        }

        public Criteria andWorkCycleIdNotIn(List<Integer> values) {
            addCriterion("work_cycle.work_cycle_id not in", values, "workCycleId");
            return (Criteria) this;
        }

        public Criteria andWorkCycleIdBetween(Integer value1, Integer value2) {
            addCriterion("work_cycle.work_cycle_id between", value1, value2, "workCycleId");
            return (Criteria) this;
        }

        public Criteria andWorkCycleIdNotBetween(Integer value1, Integer value2) {
            addCriterion("work_cycle.work_cycle_id not between", value1, value2, "workCycleId");
            return (Criteria) this;
        }

        public Criteria andWorkCycleNameIsNull() {
            addCriterion("work_cycle.work_cycle_name is null");
            return (Criteria) this;
        }

        public Criteria andWorkCycleNameIsNotNull() {
            addCriterion("work_cycle.work_cycle_name is not null");
            return (Criteria) this;
        }

        public Criteria andWorkCycleNameEqualTo(String value) {
            addCriterion("work_cycle.work_cycle_name =", value, "workCycleName");
            return (Criteria) this;
        }

        public Criteria andWorkCycleNameNotEqualTo(String value) {
            addCriterion("work_cycle.work_cycle_name <>", value, "workCycleName");
            return (Criteria) this;
        }

        public Criteria andWorkCycleNameGreaterThan(String value) {
            addCriterion("work_cycle.work_cycle_name >", value, "workCycleName");
            return (Criteria) this;
        }

        public Criteria andWorkCycleNameGreaterThanOrEqualTo(String value) {
            addCriterion("work_cycle.work_cycle_name >=", value, "workCycleName");
            return (Criteria) this;
        }

        public Criteria andWorkCycleNameLessThan(String value) {
            addCriterion("work_cycle.work_cycle_name <", value, "workCycleName");
            return (Criteria) this;
        }

        public Criteria andWorkCycleNameLessThanOrEqualTo(String value) {
            addCriterion("work_cycle.work_cycle_name <=", value, "workCycleName");
            return (Criteria) this;
        }

        public Criteria andWorkCycleNameLike(String value) {
            addCriterion("work_cycle.work_cycle_name like", value, "workCycleName");
            return (Criteria) this;
        }

        public Criteria andWorkCycleNameNotLike(String value) {
            addCriterion("work_cycle.work_cycle_name not like", value, "workCycleName");
            return (Criteria) this;
        }

        public Criteria andWorkCycleNameIn(List<String> values) {
            addCriterion("work_cycle.work_cycle_name in", values, "workCycleName");
            return (Criteria) this;
        }

        public Criteria andWorkCycleNameNotIn(List<String> values) {
            addCriterion("work_cycle.work_cycle_name not in", values, "workCycleName");
            return (Criteria) this;
        }

        public Criteria andWorkCycleNameBetween(String value1, String value2) {
            addCriterion("work_cycle.work_cycle_name between", value1, value2, "workCycleName");
            return (Criteria) this;
        }

        public Criteria andWorkCycleNameNotBetween(String value1, String value2) {
            addCriterion("work_cycle.work_cycle_name not between", value1, value2, "workCycleName");
            return (Criteria) this;
        }

        public Criteria andImgAddrIsNull() {
            addCriterion("work_cycle.img_addr is null");
            return (Criteria) this;
        }

        public Criteria andImgAddrIsNotNull() {
            addCriterion("work_cycle.img_addr is not null");
            return (Criteria) this;
        }

        public Criteria andImgAddrEqualTo(String value) {
            addCriterion("work_cycle.img_addr =", value, "imgAddr");
            return (Criteria) this;
        }

        public Criteria andImgAddrNotEqualTo(String value) {
            addCriterion("work_cycle.img_addr <>", value, "imgAddr");
            return (Criteria) this;
        }

        public Criteria andImgAddrGreaterThan(String value) {
            addCriterion("work_cycle.img_addr >", value, "imgAddr");
            return (Criteria) this;
        }

        public Criteria andImgAddrGreaterThanOrEqualTo(String value) {
            addCriterion("work_cycle.img_addr >=", value, "imgAddr");
            return (Criteria) this;
        }

        public Criteria andImgAddrLessThan(String value) {
            addCriterion("work_cycle.img_addr <", value, "imgAddr");
            return (Criteria) this;
        }

        public Criteria andImgAddrLessThanOrEqualTo(String value) {
            addCriterion("work_cycle.img_addr <=", value, "imgAddr");
            return (Criteria) this;
        }

        public Criteria andImgAddrLike(String value) {
            addCriterion("work_cycle.img_addr like", value, "imgAddr");
            return (Criteria) this;
        }

        public Criteria andImgAddrNotLike(String value) {
            addCriterion("work_cycle.img_addr not like", value, "imgAddr");
            return (Criteria) this;
        }

        public Criteria andImgAddrIn(List<String> values) {
            addCriterion("work_cycle.img_addr in", values, "imgAddr");
            return (Criteria) this;
        }

        public Criteria andImgAddrNotIn(List<String> values) {
            addCriterion("work_cycle.img_addr not in", values, "imgAddr");
            return (Criteria) this;
        }

        public Criteria andImgAddrBetween(String value1, String value2) {
            addCriterion("work_cycle.img_addr between", value1, value2, "imgAddr");
            return (Criteria) this;
        }

        public Criteria andImgAddrNotBetween(String value1, String value2) {
            addCriterion("work_cycle.img_addr not between", value1, value2, "imgAddr");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table work_cycle
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table work_cycle
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}