package com.chinamobile.iot.lightapp.mysql.dao;

import com.chinamobile.iot.lightapp.mysql.model.Applys;
import com.chinamobile.iot.lightapp.mysql.model.ApplysExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ApplysMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table applys
     *
     * @mbg.generated
     */
    long countByExample(ApplysExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table applys
     *
     * @mbg.generated
     */
    int deleteByExample(ApplysExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table applys
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer applyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table applys
     *
     * @mbg.generated
     */
    int insert(Applys record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table applys
     *
     * @mbg.generated
     */
    int insertSelective(Applys record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table applys
     *
     * @mbg.generated
     */
    List<Applys> selectByExample(ApplysExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table applys
     *
     * @mbg.generated
     */
    Applys selectByPrimaryKey(Integer applyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table applys
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Applys record, @Param("example") ApplysExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table applys
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Applys record, @Param("example") ApplysExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table applys
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Applys record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table applys
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Applys record);
}