package com.chinamobile.iot.lightapp.mysql.dao;

import com.chinamobile.iot.lightapp.mysql.dto.ApplyUserDTO;
import com.chinamobile.iot.lightapp.mysql.model.ApplyExample;

import java.util.List;

public interface ApplyMapperExt {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apply
     *
     * @mbg.generated
     */
    List<ApplyUserDTO> selectByExample(ApplyExample example);

}