package com.chinamobile.iot.lightapp.mysql.dao;

import com.chinamobile.iot.lightapp.mysql.model.CheckItem;
import com.chinamobile.iot.lightapp.mysql.model.CheckItemExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CheckItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table check_item
     *
     * @mbg.generated
     */
    long countByExample(CheckItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table check_item
     *
     * @mbg.generated
     */
    int deleteByExample(CheckItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table check_item
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer checkItemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table check_item
     *
     * @mbg.generated
     */
    int insert(CheckItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table check_item
     *
     * @mbg.generated
     */
    int insertSelective(CheckItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table check_item
     *
     * @mbg.generated
     */
    List<CheckItem> selectByExample(CheckItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table check_item
     *
     * @mbg.generated
     */
    CheckItem selectByPrimaryKey(Integer checkItemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table check_item
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") CheckItem record, @Param("example") CheckItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table check_item
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") CheckItem record, @Param("example") CheckItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table check_item
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CheckItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table check_item
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CheckItem record);
}