package com.chinamobile.iot.lightapp.mysql.dao;

import com.chinamobile.iot.lightapp.mysql.model.CheckItems;
import com.chinamobile.iot.lightapp.mysql.model.CheckItemsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CheckItemsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table check_items
     *
     * @mbg.generated
     */
    long countByExample(CheckItemsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table check_items
     *
     * @mbg.generated
     */
    int deleteByExample(CheckItemsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table check_items
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer checkItemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table check_items
     *
     * @mbg.generated
     */
    int insert(CheckItems record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table check_items
     *
     * @mbg.generated
     */
    int insertSelective(CheckItems record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table check_items
     *
     * @mbg.generated
     */
    List<CheckItems> selectByExample(CheckItemsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table check_items
     *
     * @mbg.generated
     */
    CheckItems selectByPrimaryKey(Integer checkItemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table check_items
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") CheckItems record, @Param("example") CheckItemsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table check_items
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") CheckItems record, @Param("example") CheckItemsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table check_items
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CheckItems record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table check_items
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CheckItems record);
}