package com.chinamobile.iot.lightapp.mysql.dao;

import com.chinamobile.iot.lightapp.mysql.model.Diagrams;
import com.chinamobile.iot.lightapp.mysql.model.DiagramsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DiagramsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table diagrams
     *
     * @mbg.generated
     */
    long countByExample(DiagramsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table diagrams
     *
     * @mbg.generated
     */
    int deleteByExample(DiagramsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table diagrams
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer diagramId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table diagrams
     *
     * @mbg.generated
     */
    int insert(Diagrams record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table diagrams
     *
     * @mbg.generated
     */
    int insertSelective(Diagrams record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table diagrams
     *
     * @mbg.generated
     */
    List<Diagrams> selectByExample(DiagramsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table diagrams
     *
     * @mbg.generated
     */
    Diagrams selectByPrimaryKey(Integer diagramId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table diagrams
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Diagrams record, @Param("example") DiagramsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table diagrams
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Diagrams record, @Param("example") DiagramsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table diagrams
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Diagrams record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table diagrams
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Diagrams record);
}