package com.chinamobile.iot.lightapp.mysql.dao;

import com.chinamobile.iot.lightapp.mysql.model.Notices;
import com.chinamobile.iot.lightapp.mysql.model.NoticesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface NoticesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notices
     *
     * @mbg.generated
     */
    long countByExample(NoticesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notices
     *
     * @mbg.generated
     */
    int deleteByExample(NoticesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notices
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer noticeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notices
     *
     * @mbg.generated
     */
    int insert(Notices record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notices
     *
     * @mbg.generated
     */
    int insertSelective(Notices record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notices
     *
     * @mbg.generated
     */
    List<Notices> selectByExample(NoticesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notices
     *
     * @mbg.generated
     */
    Notices selectByPrimaryKey(Integer noticeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notices
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Notices record, @Param("example") NoticesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notices
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Notices record, @Param("example") NoticesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notices
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Notices record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notices
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Notices record);
}