package com.chinamobile.iot.lightapp.mysql.dao;

import com.chinamobile.iot.lightapp.mysql.model.Period;
import com.chinamobile.iot.lightapp.mysql.model.PeriodExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PeriodMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table period
     *
     * @mbg.generated
     */
    long countByExample(PeriodExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table period
     *
     * @mbg.generated
     */
    int deleteByExample(PeriodExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table period
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer periodId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table period
     *
     * @mbg.generated
     */
    int insert(Period record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table period
     *
     * @mbg.generated
     */
    int insertSelective(Period record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table period
     *
     * @mbg.generated
     */
    List<Period> selectByExample(PeriodExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table period
     *
     * @mbg.generated
     */
    Period selectByPrimaryKey(Integer periodId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table period
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Period record, @Param("example") PeriodExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table period
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Period record, @Param("example") PeriodExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table period
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Period record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table period
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Period record);
}