package com.chinamobile.iot.lightapp.mysql.dao;

import com.chinamobile.iot.lightapp.mysql.dto.PeriodDTO;
import com.chinamobile.iot.lightapp.mysql.model.Period;
import com.chinamobile.iot.lightapp.mysql.model.PeriodExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface PeriodMapperExt {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table period
     *
     * @mbg.generated
     */
    List<PeriodDTO> selectByExample(PeriodExample example);
}