package com.chinamobile.iot.lightapp.mysql.dao;

import com.chinamobile.iot.lightapp.mysql.model.Periods;
import com.chinamobile.iot.lightapp.mysql.model.PeriodsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PeriodsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table periods
     *
     * @mbg.generated
     */
    long countByExample(PeriodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table periods
     *
     * @mbg.generated
     */
    int deleteByExample(PeriodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table periods
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer periodId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table periods
     *
     * @mbg.generated
     */
    int insert(Periods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table periods
     *
     * @mbg.generated
     */
    int insertSelective(Periods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table periods
     *
     * @mbg.generated
     */
    List<Periods> selectByExample(PeriodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table periods
     *
     * @mbg.generated
     */
    Periods selectByPrimaryKey(Integer periodId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table periods
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Periods record, @Param("example") PeriodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table periods
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Periods record, @Param("example") PeriodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table periods
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Periods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table periods
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Periods record);
}