package com.chinamobile.iot.lightapp.mysql.dao;

import com.chinamobile.iot.lightapp.mysql.dto.RegionDTO;
import com.chinamobile.iot.lightapp.mysql.model.Region;
import com.chinamobile.iot.lightapp.mysql.model.RegionExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface RegionMapperExt {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table region
     *
     * @mbg.generated
     */
    List<RegionDTO> selectByExample(RegionExample example);


}