package com.chinamobile.iot.lightapp.mysql.dao;

import com.chinamobile.iot.lightapp.mysql.model.Regions;
import com.chinamobile.iot.lightapp.mysql.model.RegionsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RegionsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table regions
     *
     * @mbg.generated
     */
    long countByExample(RegionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table regions
     *
     * @mbg.generated
     */
    int deleteByExample(RegionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table regions
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer regionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table regions
     *
     * @mbg.generated
     */
    int insert(Regions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table regions
     *
     * @mbg.generated
     */
    int insertSelective(Regions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table regions
     *
     * @mbg.generated
     */
    List<Regions> selectByExample(RegionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table regions
     *
     * @mbg.generated
     */
    Regions selectByPrimaryKey(Integer regionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table regions
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Regions record, @Param("example") RegionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table regions
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Regions record, @Param("example") RegionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table regions
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Regions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table regions
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Regions record);
}