package com.chinamobile.iot.lightapp.mysql.dao;

import com.chinamobile.iot.lightapp.mysql.model.ReportItem;
import com.chinamobile.iot.lightapp.mysql.model.ReportItemExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ReportItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_item
     *
     * @mbg.generated
     */
    long countByExample(ReportItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_item
     *
     * @mbg.generated
     */
    int deleteByExample(ReportItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_item
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer itemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_item
     *
     * @mbg.generated
     */
    int insert(ReportItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_item
     *
     * @mbg.generated
     */
    int insertSelective(ReportItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_item
     *
     * @mbg.generated
     */
    List<ReportItem> selectByExample(ReportItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_item
     *
     * @mbg.generated
     */
    ReportItem selectByPrimaryKey(Integer itemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_item
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ReportItem record, @Param("example") ReportItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_item
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ReportItem record, @Param("example") ReportItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_item
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ReportItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_item
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ReportItem record);
}