package com.chinamobile.iot.lightapp.mysql.dao;

import com.chinamobile.iot.lightapp.mysql.model.ReportItemScore;
import com.chinamobile.iot.lightapp.mysql.model.ReportItemScoreExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ReportItemScoreMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_item_score
     *
     * @mbg.generated
     */
    long countByExample(ReportItemScoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_item_score
     *
     * @mbg.generated
     */
    int deleteByExample(ReportItemScoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_item_score
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer reportItemScoreId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_item_score
     *
     * @mbg.generated
     */
    int insert(ReportItemScore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_item_score
     *
     * @mbg.generated
     */
    int insertSelective(ReportItemScore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_item_score
     *
     * @mbg.generated
     */
    List<ReportItemScore> selectByExample(ReportItemScoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_item_score
     *
     * @mbg.generated
     */
    ReportItemScore selectByPrimaryKey(Integer reportItemScoreId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_item_score
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ReportItemScore record, @Param("example") ReportItemScoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_item_score
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ReportItemScore record, @Param("example") ReportItemScoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_item_score
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ReportItemScore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_item_score
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ReportItemScore record);
}