package com.chinamobile.iot.lightapp.mysql.dao;

import com.chinamobile.iot.lightapp.mysql.model.ReportItems;
import com.chinamobile.iot.lightapp.mysql.model.ReportItemsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ReportItemsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_items
     *
     * @mbg.generated
     */
    long countByExample(ReportItemsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_items
     *
     * @mbg.generated
     */
    int deleteByExample(ReportItemsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_items
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer itemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_items
     *
     * @mbg.generated
     */
    int insert(ReportItems record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_items
     *
     * @mbg.generated
     */
    int insertSelective(ReportItems record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_items
     *
     * @mbg.generated
     */
    List<ReportItems> selectByExample(ReportItemsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_items
     *
     * @mbg.generated
     */
    ReportItems selectByPrimaryKey(Integer itemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_items
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ReportItems record, @Param("example") ReportItemsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_items
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ReportItems record, @Param("example") ReportItemsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_items
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ReportItems record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_items
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ReportItems record);
}