package com.chinamobile.iot.lightapp.mysql.dao;

import com.chinamobile.iot.lightapp.mysql.model.Reports;
import com.chinamobile.iot.lightapp.mysql.model.ReportsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ReportsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reports
     *
     * @mbg.generated
     */
    long countByExample(ReportsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reports
     *
     * @mbg.generated
     */
    int deleteByExample(ReportsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reports
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer reportId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reports
     *
     * @mbg.generated
     */
    int insert(Reports record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reports
     *
     * @mbg.generated
     */
    int insertSelective(Reports record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reports
     *
     * @mbg.generated
     */
    List<Reports> selectByExample(ReportsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reports
     *
     * @mbg.generated
     */
    Reports selectByPrimaryKey(Integer reportId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reports
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Reports record, @Param("example") ReportsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reports
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Reports record, @Param("example") ReportsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reports
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Reports record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reports
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Reports record);
}