package com.chinamobile.iot.lightapp.mysql.dao;

import com.chinamobile.iot.lightapp.mysql.dto.UserWorkcycleDTO;
import com.chinamobile.iot.lightapp.mysql.model.UserWorkcycleExample;

import java.util.List;

public interface UserWorkcycleMapperExt {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_workcycle
     *
     * @mbg.generated
     */
    List<UserWorkcycleDTO> selectByExample(UserWorkcycleExample example);


}