package com.chinamobile.iot.lightapp.mysql.dao;

import com.chinamobile.iot.lightapp.mysql.model.UserWorkcycle;
import com.chinamobile.iot.lightapp.mysql.model.UserWorkcycleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserWorkcycleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_workcycle
     *
     * @mbg.generated
     */
    long countByExample(UserWorkcycleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_workcycle
     *
     * @mbg.generated
     */
    int deleteByExample(UserWorkcycleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_workcycle
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer relationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_workcycle
     *
     * @mbg.generated
     */
    int insert(UserWorkcycle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_workcycle
     *
     * @mbg.generated
     */
    int insertSelective(UserWorkcycle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_workcycle
     *
     * @mbg.generated
     */
    List<UserWorkcycle> selectByExample(UserWorkcycleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_workcycle
     *
     * @mbg.generated
     */
    UserWorkcycle selectByPrimaryKey(Integer relationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_workcycle
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") UserWorkcycle record, @Param("example") UserWorkcycleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_workcycle
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") UserWorkcycle record, @Param("example") UserWorkcycleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_workcycle
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(UserWorkcycle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_workcycle
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(UserWorkcycle record);
}