package com.chinamobile.iot.lightapp.mysql.dao;

import com.chinamobile.iot.lightapp.mysql.dto.WorkCycleDTO;
import com.chinamobile.iot.lightapp.mysql.model.WorkCycleExample;

import java.util.List;

public interface WorkCycleMapperExt {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_cycle
     *
     * @mbg.generated
     */
    List<WorkCycleDTO> selectByExample(WorkCycleExample example);
}