package com.chinamobile.iot.lightapp.mysql.dao;

import com.chinamobile.iot.lightapp.mysql.model.WorkCycle;
import com.chinamobile.iot.lightapp.mysql.model.WorkCycleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WorkCycleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_cycle
     *
     * @mbg.generated
     */
    long countByExample(WorkCycleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_cycle
     *
     * @mbg.generated
     */
    int deleteByExample(WorkCycleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_cycle
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer workCycleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_cycle
     *
     * @mbg.generated
     */
    int insert(WorkCycle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_cycle
     *
     * @mbg.generated
     */
    int insertSelective(WorkCycle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_cycle
     *
     * @mbg.generated
     */
    List<WorkCycle> selectByExample(WorkCycleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_cycle
     *
     * @mbg.generated
     */
    WorkCycle selectByPrimaryKey(Integer workCycleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_cycle
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") WorkCycle record, @Param("example") WorkCycleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_cycle
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") WorkCycle record, @Param("example") WorkCycleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_cycle
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(WorkCycle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_cycle
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(WorkCycle record);
}